from enum import Enum


class EventSubTopics(Enum):
    """
    Enums for EventSub topics.
    Based on this listing on twitch.tv's EventSub documentation:
    https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/
    """
    AUTOMOD_MESSAGE_HOLD_V1 = ('automod.message.hold', '1')
    AUTOMOD_MESSAGE_HOLD_V2 = ('automod.message.hold', '2')
    AUTOMOD_MESSAGE_UPDATE_V1 = ('automod.message.update', '1')
    AUTOMOD_MESSAGE_UPDATE_V2 = ('automod.message.update', '2')
    AUTOMOD_SETTINGS_UPDATE_V1 = ('automod.settings.update', '1')
    AUTOMOD_TERMS_UPDATE_V1 = ('automod.terms.update', '1')
    CHANNEL_BITS_USE_V1 = ('channel.bits.use', '1')
    CHANNEL_UPDATE_V2 = ('channel.update', '2')
    CHANNEL_FOLLOW_V2 = ('channel.follow', '2')
    CHANNEL_AD_BREAK_BEGIN_V1 = ('channel.ad_break.begin', '1')
    CHANNEL_CHAT_CLEAR_V1 = ('channel.chat.clear', '1')
    CHANNEL_CHAT_CLEAR_USER_MESSAGES_V1 = ('channel.chat.clear_user_messages', '1')
    CHANNEL_CHAT_MESSAGE_V1 = ('channel.chat.message', '1')
    CHANNEL_CHAT_MESSAGE_DELETE_V1 = ('channel.chat.message_delete', '1')
    CHANNEL_CHAT_NOTIFICATION_V1 = ('channel.chat.notification', '1')
    CHANNEL_CHAT_SETTINGS_UPDATE_V1 = ('channel.chat_settings.update', '1')
    CHANNEL_CHAT_USER_MESSAGE_HOLD_V1 = ('channel.chat.user_message_hold', '1')
    CHANNEL_CHAT_USER_MESSAGE_UPDATE_V1 = ('channel.chat.user_message_update', '1')
    CHANNEL_SHARED_CHAT_BEGIN_V1 = ('channel.shared_chat.begin', '1')
    CHANNEL_SHARED_CHAT_UPDATE_V1 = ('channel.shared_chat.update', '1')
    CHANNEL_SHARED_CHAT_END_V1 = ('channel.shared_chat.end', '1')
    CHANNEL_SUBSCRIBE = ('channel.subscribe', '1')
    CHANNEL_SUBSCRIPTION_END_V1 = ('channel.subscription.end', '1')
    CHANNEL_SUBSCRIPTION_GIFT_V1 = ('channel.subscription.gift', '1')
    CHANNEL_SUBSCRIPTION_MESSAGE_V1 = ('channel.subscription.message', '1')
    CHANNEL_CHEER_V1 = ('channel.cheer', '1')
    CHANNEL_RAID_V1 = ('channel.raid', '1')
    CHANNEL_UNBAN_V1 = ('channel.unban', '1')
    CHANNEL_UNBAN_REQUEST_CREATE_V1 = ('channel.unban_request.create', '1')
    CHANNEL_UNBAN_REQUEST_RESOLVE_V1 = ('channel.unban_request.resolve', '1')
    CHANNEL_MODERATE_V1 = ('channel.moderate', '1')
    CHANNEL_MODERATE_V2 = ('channel.moderate', '2')
    CHANNEL_MODERATOR_ADD_V1 = ('channel.moderator.add', '1')
    CHANNEL_MODERATOR_REMOVE_V1 = ('channel.moderator.remove', '1')
    CHANNEL_GUEST_STAR_SESSION_BEGIN_BETA = ('channel.guest_star_session.begin', 'beta')
    CHANNEL_GUEST_STAR_SESSION_END_BETA = ('channel.guest_star_session.end', 'beta')
    CHANNEL_GUEST_STAR_GUEST_UPDATE_BETA = ('channel.guest_star_guest.update', 'beta')
    CHANNEL_GUEST_STAR_SETTINGS_UPDATE_BETA = ('channel.guest_star_settings.update', 'beta')
    CHANNEL_CHANNEL_POINTS_AUTOMATIC_REWARD_REDEMPTION_ADD_V1 = ('channel.channel_points_automatic_reward_redemption.add', '1')
    CHANNEL_CHANNEL_POINTS_AUTOMATIC_REWARD_REDEMPTION_ADD_V2 = ('channel.channel_points_automatic_reward_redemption.add', '2')
    CHANNEL_CHANNEL_POINTS_CUSTOM_REWARD_ADD_V1 = ('channel.channel_points_custom_reward.add', '1')
    CHANNEL_CHANNEL_POINTS_CUSTOM_REWARD_UPDATE_V1 = ('channel.channel_points_custom_reward.update', '1')
    CHANNEL_CHANNEL_POINTS_CUSTOM_REWARD_REMOVE_V1 = ('channel.channel_points_custom_reward.remove', '1')
    CHANNEL_CHANNEL_POINTS_CUSTOM_REWARD_REDEMPTION_ADD_V1 = ('channel.channel_points_custom_reward_redemption.add', '1')
    CHANNEL_CHANNEL_POINTS_CUSTOM_REWARD_REDEMPTION_UPDATE_V1 = ('channel.channel_points_custom_reward_redemption.update', '1')
    CHANNEL_POLL_BEGIN_V1 = ('channel.poll.begin', '1')
    CHANNEL_POLL_PROGRESS_V1 = ('channel.poll.progress', '1')
    CHANNEL_POLL_END_V1 = ('channel.poll.end', '1')
    CHANNEL_PREDICTION_BEGIN_V1 = ('channel.prediction.begin', '1')
    CHANNEL_PREDICTION_PROGRESS_V1 = ('channel.prediction.progress', '1')
    CHANNEL_PREDICTION_LOCK_V1 = ('channel.prediction.lock', '1')
    CHANNEL_PREDICTION_END_V1 = ('channel.prediction.end', '1')
    CHANNEL_SUSPICIOUS_USER_MESSAGE_V1 = ('channel.suspicious_user.message', '1')
    CHANNEL_SUSPICIOUS_USER_UPDATE_V1 = ('channel.suspicious_user.update', '1')
    CHANNEL_VIP_ADD_V1 = ('channel.vip.add', '1')
    CHANNEL_VIP_REMOVE_V1 = ('channel.vip.remove', '1')
    CHANNEL_WARNING_ACKNOWLEDGE_V1 = ('channel.warning.acknowledge', '1')
    CHANNEL_WARNING_SEND_V1 = ('channel.warning.send', '1')
    CHANNEL_CHARITY_CAMPAIGN_DONATE_V1 = ('channel.charity_campaign.donate', '1')
    CHANNEL_CHARITY_CAMPAIGN_START_V1 = ('channel.charity_campaign.start', '1')
    CHANNEL_CHARITY_CAMPAIGN_PROGRESS_V1 = ('channel.charity_campaign.progress', '1')
    CHANNEL_CHARITY_CAMPAIGN_STOP_V1 = ('channel.charity_campaign.stop', '1')
    CONDUIT_SHARD_DISABLED_V1 = ('conduit.shard.disabled', '1')
    DROP_ENTITLEMENT_GRANT_V1 = ('drop.entitlement.grant', '1')
    EXTENSION_BITS_TRANSACTION_CREATE_V1 = ('extension.bits_transaction.create', '1')
    CHANNEL_GOAL_BEGIN_V1 = ('channel.goal.begin', '1')
    CHANNEL_GOAL_PROGRESS_V1 = ('channel.goal.progress', '1')
    CHANNEL_GOAL_END_V1 = ('channel.goal.end', '1')
    CHANNEL_HYPE_TRAIN_BEGIN_V2 = ('channel.hype_train.begin', '2')
    CHANNEL_HYPE_TRAIN_PROGRESS_V2 = ('channel.hype_train.progress', '2')
    CHANNEL_HYPE_TRAIN_END_V2 = ('channel.hype_train.end', '2')
    CHANNEL_SHIELD_MODE_BEGIN_V1 = ('channel.shield_mode.begin', '1')
    CHANNEL_SHIELD_MODE_END_V1 = ('channel.shield_mode.end', '1')
    CHANNEL_SHOUTOUT_CREATE_V1 = ('channel.shoutout.create', '1')
    CHANNEL_SHOUTOUT_RECEIVE_V1 = ('channel.shoutout.receive', '1')
    STREAM_ONLINE_V1 = ('stream.online', '1')
    STREAM_OFFLINE_V1 = ('stream.offline', '1')
    USER_AUTHORIZATION_GRANT_V1 = ('user.authorization.grant', '1')
    USER_AUTHORIZATION_REVOKE_V1 = ('user.authorization.revoke', '1')
    USER_UPDATE_V1 = ('user.update', '1')
    USER_WHISPER_MESSAGE_V1 = ('user.whisper.message', '1')



